### PR TITLE
Remove alerts and replace with changing button text for addContact()

### PR DESCRIPTION
**Pull request by jplotz**
I removed the alerts from the edit function because it already has error text if the format of the new contact information is invalid. I removed some of the alerts from addContact() and switched the success alert to a temporary change of the text of the button for 2 seconds to a message "Success!"

### CODE REVIEW

**Comment by jplotz** [comment]
edit: i forgot to remove the alert on line 860

**Comment by mistrynick** [comment]
Screenshot 2024-06-03 at 10 10 13 PM

I was looking at this variant of implementation as well, can i see how your implementation looks like. Either way it is good and it shouldnt be a problem.

**Comment by jplotz** [comment]
here's a video, either option is fine with me

https://github.com/The-Cliff-Face/Manager_Of_Contacts/assets/113050852/e9787993-c770-4e29-b353-8574612b58ed

**Comment by mistrynick** [comment]
ngl i find yours more aesthetically pleasing so lets do that.

**Comment by jplotz** [comment]
yours is probably better because it replaces the sign-in alerts as well

**Pull request merged**
